### ISSUE TITLE
vaultwarden_ldap configuration (config.toml) is not added to the install directory

### ISSUE THREAD

**Issue by looowizz** [looowizz/vaultwarden_ldap_ynh#1]
This is the current code, not sure what is wrong with it :/ 
https://github.com/looowizz/vaultwarden_ldap_ynh/blob/1fce45013f722dcc634f9303be816177f89e564d/scripts/install#L42-L47

**Comment by Tagadda** [comment]
I would suggest `if [ $ldap_enabled -eq 1]; then ` (without the double quotes around the variable)

**Comment by oceanfabreeze** [comment]
I'm assuming the ldap_enabled variable is defined/initialized in the sourcing you're doing in the first lines of the script. 

I wouldn't think the quotes around the variable matter here, as it just allows the variable to have whitespace or special characters defined. It's actually probably better coding practice to leave them in. 
BUT of course since you're expecting a 0 or 1 , they could be removed. 

1.  All of the if conditionals from line 42 forward need a space after the 1 and before the bracket. (Lines 42, 57, and 79)

**EXAMPLE:**
`if [ "$ldap_enabled" -eq 1]; then `
_SHOULD BE:_
`if [ "$ldap_enabled" -eq 1 ]; then `

2. `yunohost service add "vaultwarden_ldap" --description"LDAP for vaultwarden"` on line 59

Should be `yunohost service add "vaultwarden_ldap" --description="LDAP for vaultwarden"`


Give that a shot and let me know how it turns out 👍🏻

**Comment by looowizz** [comment]
Ohh i seee, thanks, will try that! :)

**Comment by looowizz** [comment]
@oceanfabreeze Thanks, that worked perfectly!

**Comment by oceanfabreeze** [comment]
Glad to be of assistance! Lmk if you need help with anything else! :) @looowizz
